apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-demo-pvc
  namespace: default
  labels:
    app: k8s-demo-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
